import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const spec = JSON.parse(await readFile(new URL('openapi.json', root), 'utf8'));
const outputUrl = new URL('../src/generated-client.ts', import.meta.url);

const refName = (ref) => ref?.split('/').pop();
const tsType = (schema = {}) => {
  if (schema.$ref) return refName(schema.$ref);
  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((value) => JSON.stringify(value)).join(' | ');
  if (schema.oneOf) return schema.oneOf.map(tsType).join(' | ');
  if (schema.allOf) return schema.allOf.map(tsType).join(' & ');
  if (Array.isArray(schema.type)) return schema.type.map((type) => tsType({ ...schema, type })).join(' | ');
  if (schema.type === 'array') return `Array<${tsType(schema.items)}>`;
  if (schema.type === 'object' || schema.properties) {
    const required = new Set(schema.required ?? []);
    const fields = Object.entries(schema.properties ?? {}).map(([name, value]) =>
      `  ${JSON.stringify(name)}${required.has(name) ? '' : '?'}: ${tsType(value)};`,
    );
    if (schema.additionalProperties) fields.push(`  [key: string]: ${schema.additionalProperties === true ? 'unknown' : tsType(schema.additionalProperties)};`);
    return fields.length ? `{\n${fields.join('\n')}\n}` : 'Record<string, unknown>';
  }
  if (schema.type === 'null') return 'null';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  return 'string';
};

const responseType = (operation) => {
  const success = Object.entries(operation.responses ?? {}).find(([status]) => /^2/.test(status))?.[1];
  const schema = success?.content?.['application/json']?.schema;
  return schema ? tsType(schema) : 'void';
};

const pathParams = (path) => [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]);
const operations = [];
for (const [path, item] of Object.entries(spec.paths ?? {})) {
  for (const method of ['get', 'post', 'put', 'patch', 'delete']) {
    const operation = item[method];
    if (!operation) continue;
    operations.push({ path, method, operation, params: pathParams(path) });
  }
}

const schemaTypes = Object.entries(spec.components?.schemas ?? {})
  .map(([name, schema]) => `export type ${name} = ${tsType(schema)};`)
  .join('\n\n');

const operationTypes = operations.map(({ operation, params }) => {
  const fields = params.map((name) => `  ${JSON.stringify(name)}: string;`);
  const input = fields.length ? `{\n${fields.join('\n')}\n} & RequestOptions` : 'RequestOptions';
  return `export type ${operation.operationId}Input = ${input};\nexport type ${operation.operationId}Output = ${responseType(operation)};`;
}).join('\n\n');

const methods = operations.map(({ path, method, operation, params }) => {
  const fields = params.map((name) => `  ${JSON.stringify(name)}: string;`).join('\n');
  const input = params.length ? `{\n${fields}\n} & RequestOptions` : 'RequestOptions';
  return `  async ${operation.operationId}(input: ${input}): Promise<ApiResponse<${responseType(operation)}>> {\n    return this.request<${responseType(operation)}>(${JSON.stringify(path)}, ${JSON.stringify(method.toUpperCase())}, input);\n  }`;
}).join('\n\n');

const output = `/* eslint-disable */
/**
 * Generated from ../openapi.json by scripts/generate-client.mjs.
 * Do not edit this file directly; run pnpm generate after changing the contract.
 */

export interface RequestOptions {
  body?: unknown;
  headers?: Record<string, string>;
  query?: Record<string, string | number | boolean | undefined>;
  signal?: AbortSignal;
  credentials?: RequestCredentials;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

${schemaTypes}

${operationTypes}

export class HubGitClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch = fetch) {}

  private async request<T>(template: string, method: string, input: RequestOptions): Promise<ApiResponse<T>> {
    const path = template.replace(/\\{([^}]+)\\}/g, (_, key) => encodeURIComponent(String((input as Record<string, unknown>)[key])));
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(input.query ?? {})) if (value !== undefined) query.set(key, String(value));
    const url = new URL(path + (query.size ? \`?\${query}\` : ''), this.baseUrl);
    const response = await this.fetchImpl(url, { method, credentials: input.credentials ?? 'include', headers: { Accept: 'application/json', ...(input.body === undefined ? {} : { 'Content-Type': 'application/json' }), ...input.headers }, body: input.body === undefined ? undefined : JSON.stringify(input.body), signal: input.signal });
    const data = response.status === 204 ? undefined as T : await response.json() as T;
    if (!response.ok) throw Object.assign(new Error(\`HubGit request failed with \${response.status}\`), { response, data });
    return { data, status: response.status, headers: response.headers };
  }

${methods}
}
`;

if (process.argv.includes('--check')) {
  const current = await readFile(outputUrl, 'utf8').catch(() => '');
  if (current !== output) {
    console.error(`${fileURLToPath(outputUrl)} is stale; run pnpm generate`);
    process.exit(1);
  }
} else {
  await mkdir(new URL('../src/', import.meta.url), { recursive: true });
  await writeFile(outputUrl, output);
}
