/* eslint-disable */
/**
 * Generated from ../openapi.json by scripts/generate-client.mjs.
 * Do not edit this file directly; run pnpm generate after changing the contract.
 */

export interface RequestOptions {
  body?: unknown;
  headers?: Record<string, string>;
  query?: Record<string, string | number | boolean | undefined>;
  signal?: AbortSignal;
  credentials?: RequestCredentials;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

export type ProblemDetails = {
  "type": string;
  "title": string;
  "status": number;
  "detail"?: string;
  "instance"?: string;
  "code": string;
  "fieldErrors"?: Array<FieldError>;
  "traceId"?: string;
};

export type FieldError = {
  "field": string;
  "code": string;
  "message": string;
};

export type PageInfo = {
  "startCursor"?: string | null;
  "endCursor"?: string | null;
  "hasNextPage": boolean;
  "hasPreviousPage": boolean;
};

export type ResourcePermissions = {
  "read": boolean;
  "triage"?: boolean;
  "write": boolean;
  "maintain"?: boolean;
  "admin": boolean;
};

export type CapabilitySet = {
  "provider": string;
  "version"?: string;
  "features": {
  "issues": boolean;
  "pullRequests": boolean;
  "releases": boolean;
  "wiki": boolean;
  "discussions": boolean;
  "projects": boolean;
  "actions": boolean;
  "security": boolean;
  "insights": boolean;
  "webhooks"?: boolean;
  "repositoryRules"?: boolean;
  "serverSentEvents"?: boolean;
};
  "limits"?: {
  "maxPageSize"?: number;
  "maxUploadBytes"?: number;
};
};

export type Freshness = {
  "state": "live" | "refreshing" | "stale" | "offline";
  "lastSyncedAt": string | null;
  "lastAuthorizedAt": string | null;
  "provider": string;
};

export type BrandingManifest = {
  "preset": string;
  "productName": string;
  "shortName": string;
  "logoUrl": string | null;
  "faviconUrl": string | null;
  "titleTemplate": string;
  "colors": {
  "accent": string;
  "headerBackground": string;
  [key: string]: string;
};
  "authentication": {
  "heading": string;
  "description": string;
  "connectLabel": string;
};
  "links": {
  "privacy": string | null;
  "terms": string | null;
  "source": string | null;
  "support": string | null;
};
  "notice": string | null;
  "providerDisplayNames": {
  [key: string]: string;
};
};

export type InstanceMeta = {
  "name": string;
  "baseUrl": string;
  "branding": BrandingManifest;
  "registrationEnabled": boolean;
  "version"?: string;
  "freshness"?: Freshness;
};

export type AuthProvider = {
  "id": string;
  "displayName": string;
  "enabled": boolean;
  "supportsRegistration"?: boolean;
};

export type AuthMethods = {
  "password": boolean;
  "passkey": boolean;
  "twoFactor": boolean;
  "providers": Array<AuthProvider>;
};

export type LoginRequest = {
  "login": string;
  "password": string;
  "otp"?: string;
  "remember"?: boolean;
};

export type RegisterRequest = {
  "username": string;
  "email": string;
  "password": string;
};

export type Session = {
  "authenticated": boolean;
  "csrfToken": string;
  "expiresAt": string | null;
  "viewer": Viewer | null;
};

export type Viewer = User & {
  "roles": Array<"member" | "maintainer" | "administrator">;
  "email"?: string;
  "unreadNotificationCount"?: number;
};

export type User = {
  "id": string;
  "kind": "user";
  "username": string;
  "displayName": string;
  "avatarUrl": string;
  "profileUrl": string;
  "bio"?: string | null;
  "location"?: string | null;
  "followerCount"?: number;
  "followingCount"?: number;
  "createdAt"?: string;
  "freshness"?: Freshness;
};

export type UserPage = {
  "items": Array<User>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type Organization = {
  "id": string;
  "kind": "organization";
  "login": string;
  "displayName": string;
  "description"?: string | null;
  "avatarUrl": string;
  "websiteUrl"?: string | null;
  "permissions": ResourcePermissions;
};

export type OrganizationUpdate = {
  "displayName"?: string;
  "description"?: string | null;
  "websiteUrl"?: string | null;
};

export type Team = {
  "id": string;
  "name": string;
  "slug": string;
  "permission": "read" | "triage" | "write" | "maintain" | "admin";
  "memberCount": number;
};

export type TeamPage = {
  "items": Array<Team>;
  "pageInfo": PageInfo;
};

export type Repository = {
  "id": string;
  "kind": "repository";
  "owner": RepositoryOwner;
  "name": string;
  "fullName": string;
  "description"?: string | null;
  "visibility": "public" | "internal" | "private";
  "defaultBranch": string;
  "empty": boolean;
  "archived": boolean;
  "fork"?: boolean;
  "forkedFrom"?: string | null;
  "language"?: string | null;
  "license"?: string | null;
  "topics"?: Array<string>;
  "permissions": ResourcePermissions;
  "counts": RepositoryCounts;
  "cloneUrls": CloneUrls;
  "createdAt": string;
  "updatedAt": string;
  "pushedAt"?: string | null;
  "freshness"?: Freshness;
};

export type RepositoryOwner = {
  "id": string;
  "kind": "user" | "organization";
  "login": string;
  "avatarUrl": string;
};

export type RepositoryCounts = {
  "stars": number;
  "forks": number;
  "watchers": number;
  "issues": number;
  "pullRequests": number;
};

export type CloneUrls = {
  "http": string;
  "ssh": string;
};

export type RepositoryCreate = {
  "owner": string;
  "name": string;
  "description"?: string | null;
  "visibility": "public" | "internal" | "private";
  "initialize"?: boolean;
};

export type RepositoryUpdate = {
  "name"?: string;
  "description"?: string | null;
  "visibility"?: "public" | "internal" | "private";
  "defaultBranch"?: string;
  "archived"?: boolean;
  "features"?: RepositoryFeatures;
};

export type RepositoryFeatures = {
  "issues"?: boolean;
  "wiki"?: boolean;
  "discussions"?: boolean;
  "projects"?: boolean;
};

export type RepositoryPage = {
  "items": Array<Repository>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type Dashboard = {
  "repositories": RepositoryPage;
  "activity": Array<TimelineEvent>;
};

export type GitRef = {
  "name": string;
  "kind": "branch" | "tag";
  "sha": string;
  "protected": boolean;
  "aheadBy"?: number;
  "behindBy"?: number;
};

export type RefPage = {
  "items": Array<GitRef>;
  "pageInfo": PageInfo;
};

export type GitTree = {
  "sha": string;
  "ref": string;
  "path": string;
  "entries": Array<TreeEntry>;
  "commit": CommitSummary;
};

export type TreeEntry = {
  "name": string;
  "path": string;
  "kind": "file" | "directory" | "symlink" | "submodule";
  "sha": string;
  "size"?: number | null;
  "lastCommit"?: CommitSummary;
};

export type GitBlob = {
  "sha": string;
  "path": string;
  "size": number;
  "binary": boolean;
  "truncated": boolean;
  "encoding": "utf-8" | "base64";
  "content"?: string | null;
  "language"?: string | null;
  "lfs"?: boolean;
};

export type CommitSummary = {
  "sha": string;
  "shortSha": string;
  "message": string;
  "author": GitActor;
  "authoredAt": string;
  "verification"?: Verification;
};

export type GitActor = {
  "name": string;
  "email": string;
  "user"?: User | null;
};

export type Verification = {
  "verified": boolean;
  "reason"?: string | null;
  "signatureType"?: "gpg" | "ssh" | "smime" | null;
};

export type CommitDetail = CommitSummary & {
  "parents": Array<string>;
  "committer": GitActor;
  "committedAt": string;
  "body"?: string;
  "stats": DiffStats;
  "files": Array<DiffFile>;
};

export type CommitPage = {
  "items": Array<CommitSummary>;
  "pageInfo": PageInfo;
};

export type DiffStats = {
  "additions": number;
  "deletions": number;
  "filesChanged": number;
};

export type DiffFile = {
  "oldPath": string | null;
  "newPath": string | null;
  "status": "added" | "modified" | "deleted" | "renamed" | "copied";
  "binary": boolean;
  "additions": number;
  "deletions": number;
  "hunks": Array<DiffHunk>;
};

export type DiffHunk = {
  "header": string;
  "lines": Array<DiffLine>;
};

export type DiffLine = {
  "kind": "context" | "addition" | "deletion" | "no-newline";
  "oldLine"?: number | null;
  "newLine"?: number | null;
  "content": string;
};

export type DiffFilePage = {
  "items": Array<DiffFile>;
  "pageInfo": PageInfo;
};

export type Comparison = {
  "status": "identical" | "ahead" | "behind" | "diverged";
  "aheadBy": number;
  "behindBy": number;
  "mergeBaseSha"?: string | null;
  "commits": Array<CommitSummary>;
  "files": Array<DiffFile>;
  "stats": DiffStats;
};

export type Blame = {
  "path": string;
  "ranges": Array<{
  "startLine": number;
  "endLine": number;
  "commit": CommitSummary;
}>;
};

export type Label = {
  "id": string;
  "name": string;
  "color": string;
  "description": string;
};

export type LabelWrite = {
  "name": string;
  "color": string;
  "description"?: string;
};

export type LabelPage = {
  "items": Array<Label>;
  "pageInfo": PageInfo;
};

export type Milestone = {
  "id": string;
  "number": number;
  "title": string;
  "description"?: string | null;
  "state": "open" | "closed";
  "dueAt"?: string | null;
  "openIssueCount": number;
  "closedIssueCount": number;
};

export type MilestonePage = {
  "items": Array<Milestone>;
  "pageInfo": PageInfo;
};

export type Issue = {
  "id": string;
  "kind": "issue";
  "number": number;
  "title": string;
  "body": string;
  "state": "open" | "closed";
  "stateReason"?: "completed" | "not_planned" | "reopened" | null;
  "author": User;
  "labels": Array<Label>;
  "assignees": Array<User>;
  "milestone"?: Milestone | null;
  "commentCount": number;
  "permissions": ResourcePermissions;
  "createdAt": string;
  "updatedAt": string;
  "closedAt"?: string | null;
  "freshness"?: Freshness;
};

export type IssueWrite = {
  "title"?: string;
  "body"?: string;
  "state"?: "open" | "closed";
  "stateReason"?: "completed" | "not_planned" | "reopened" | null;
  "labelIds"?: Array<string>;
  "assigneeIds"?: Array<string>;
  "milestoneId"?: string | null;
};

export type IssuePage = {
  "items": Array<Issue>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type Comment = {
  "id": string;
  "body": string;
  "author": User;
  "reactions": Array<ReactionGroup>;
  "permissions": ResourcePermissions;
  "createdAt": string;
  "updatedAt": string;
};

export type CommentWrite = {
  "body": string;
};

export type CommentPage = {
  "items": Array<Comment>;
  "pageInfo": PageInfo;
};

export type ReactionGroup = {
  "content": "+1" | "-1" | "laugh" | "hooray" | "confused" | "heart" | "rocket" | "eyes";
  "count": number;
  "viewerHasReacted": boolean;
};

export type PullRequest = {
  "id": string;
  "kind": "pullRequest";
  "number": number;
  "title": string;
  "body": string;
  "state": "open" | "closed" | "merged";
  "draft": boolean;
  "author": User;
  "base": PullRequestRef;
  "head": PullRequestRef;
  "mergeability": "mergeable" | "conflicting" | "checking" | "blocked" | "unknown";
  "reviewDecision": "approved" | "changes_requested" | "review_required" | "none";
  "checks": CheckSummary;
  "labels"?: Array<Label>;
  "permissions": ResourcePermissions;
  "createdAt": string;
  "updatedAt": string;
  "mergedAt"?: string | null;
  "freshness"?: Freshness;
};

export type PullRequestRef = {
  "repository": string;
  "ref": string;
  "sha": string;
};

export type PullRequestCreate = {
  "title": string;
  "body"?: string;
  "head": string;
  "base": string;
  "draft"?: boolean;
};

export type PullRequestPage = {
  "items": Array<PullRequest>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type CheckSummary = {
  "total": number;
  "queued": number;
  "inProgress": number;
  "successful": number;
  "failed": number;
};

export type CheckSuite = {
  "id": string;
  "name": string;
  "status": "queued" | "in_progress" | "completed";
  "conclusion": "success" | "failure" | "neutral" | "cancelled" | "skipped" | "timed_out" | null;
  "checks": Array<CheckRun>;
  "startedAt": string;
  "completedAt"?: string | null;
};

export type CheckRun = {
  "id": string;
  "name": string;
  "status": "queued" | "in_progress" | "completed";
  "conclusion": string | null;
  "detailsUrl"?: string | null;
  "summary"?: string | null;
};

export type CheckSuitePage = {
  "items": Array<CheckSuite>;
  "pageInfo": PageInfo;
};

export type Review = {
  "id": string;
  "author": User;
  "state": "commented" | "approved" | "changes_requested" | "dismissed" | "pending";
  "body": string;
  "commitSha"?: string;
  "submittedAt": string;
};

export type ReviewWrite = {
  "event": "comment" | "approve" | "request_changes";
  "body"?: string;
  "comments"?: Array<{
  "path": string;
  "line": number;
  "side"?: "left" | "right";
  "body": string;
}>;
};

export type ReviewPage = {
  "items": Array<Review>;
  "pageInfo": PageInfo;
};

export type MergeRequest = {
  "method": "merge" | "squash" | "rebase";
  "title"?: string;
  "message"?: string;
  "expectedHeadSha": string;
};

export type MergeResult = {
  "merged": boolean;
  "sha": string | null;
  "message": string;
};

export type Release = {
  "id": string;
  "tagName": string;
  "name": string;
  "body": string;
  "draft": boolean;
  "prerelease": boolean;
  "author": User;
  "assets": Array<ReleaseAsset>;
  "createdAt": string;
  "publishedAt"?: string | null;
};

export type ReleaseAsset = {
  "id": string;
  "name": string;
  "size": number;
  "contentType"?: string;
  "downloadUrl": string;
  "downloadCount": number;
};

export type ReleaseWrite = {
  "tagName": string;
  "target"?: string;
  "name": string;
  "body"?: string;
  "draft"?: boolean;
  "prerelease"?: boolean;
};

export type ReleasePage = {
  "items": Array<Release>;
  "pageInfo": PageInfo;
};

export type Discussion = {
  "id": string;
  "number": number;
  "title": string;
  "body": string;
  "category": DiscussionCategory;
  "author": User;
  "answered": boolean;
  "commentCount": number;
  "createdAt": string;
};

export type DiscussionCategory = {
  "id": string;
  "name": string;
  "slug": string;
  "emoji": string;
  "answerable"?: boolean;
};

export type DiscussionWrite = {
  "title": string;
  "body": string;
  "categoryId": string;
};

export type DiscussionPage = {
  "items": Array<Discussion>;
  "pageInfo": PageInfo;
};

export type WikiPage = {
  "id": string;
  "slug": string;
  "title": string;
  "body": string;
  "sha": string;
  "updatedAt": string;
};

export type WikiWrite = {
  "title": string;
  "body": string;
  "message"?: string;
};

export type WikiPageList = {
  "items": Array<WikiPage>;
  "cloneUrl"?: string;
};

export type Project = {
  "id": string;
  "title": string;
  "description": string;
  "closed": boolean;
  "views": Array<ProjectView>;
  "itemCount": number;
};

export type ProjectView = {
  "id": string;
  "name": string;
  "layout": "table" | "board";
};

export type ProjectWrite = {
  "title": string;
  "description"?: string;
};

export type ProjectPage = {
  "items": Array<Project>;
  "pageInfo": PageInfo;
};

export type Workflow = {
  "id": string;
  "name": string;
  "path": string;
  "state": "active" | "disabled";
};

export type WorkflowPage = {
  "items": Array<Workflow>;
  "pageInfo": PageInfo;
};

export type WorkflowDispatch = {
  "ref": string;
  "inputs"?: {
  [key: string]: string;
};
};

export type WorkflowRun = {
  "id": string;
  "name": string;
  "event": string;
  "status": "queued" | "in_progress" | "completed";
  "conclusion": string | null;
  "headSha": string;
  "jobs": Array<WorkflowJob>;
  "createdAt": string;
};

export type WorkflowJob = {
  "id": string;
  "name": string;
  "status": string;
  "conclusion": string | null;
  "steps": Array<{
  "name": string;
  "status": string;
  "conclusion"?: string | null;
}>;
  "logUrl"?: string | null;
};

export type WorkflowRunPage = {
  "items": Array<WorkflowRun>;
  "pageInfo": PageInfo;
};

export type SecurityOverview = {
  "policyEnabled": boolean;
  "dependencyAlerts": number;
  "codeScanningAlerts": number;
  "secretScanningAlerts": number;
};

export type RepositoryInsights = {
  "period": string;
  "commits": Array<TimeSeriesPoint>;
  "contributors": Array<ContributorStats>;
  "traffic": Array<TimeSeriesPoint>;
};

export type TimeSeriesPoint = {
  "at": string;
  "value": number;
};

export type ContributorStats = {
  "user": User;
  "commits": number;
  "additions": number;
  "deletions": number;
};

export type RepositoryCachePolicy = {
  "mode": "disabled" | "private" | "shared";
  "maxAgeSeconds": number;
  "staleWhileRevalidateSeconds"?: number;
};

export type RepositoryCacheStatus = {
  "state": "cold" | "warm" | "refreshing" | "error";
  "lastInvalidatedAt": string | null;
  "entryCount": number;
  "lastErrorCode"?: string | null;
};

export type RepositoryCache = {
  "policy": RepositoryCachePolicy;
  "status": RepositoryCacheStatus;
  "freshness": Freshness;
};

export type CacheInvalidation = {
  "accepted": true;
  "requestedAt": string;
  "topics"?: Array<string>;
};

export type AccessSettings = {
  "collaborators": Array<AccessGrant>;
  "teams": Array<AccessGrant>;
  "freshness"?: Freshness;
};

export type AccessGrant = {
  "subjectId": string;
  "subjectKind": "user" | "team";
  "permission": "read" | "triage" | "write" | "maintain" | "admin";
};

export type RepositoryRule = {
  "id": string;
  "name": string;
  "target": "branch" | "tag";
  "enforcement": "active" | "disabled" | "evaluate";
  "rules": Array<{
  "kind": string;
  "parameters"?: {
  [key: string]: unknown;
};
}>;
};

export type RulePage = {
  "items": Array<RepositoryRule>;
  "pageInfo": PageInfo;
};

export type Webhook = {
  "id": string;
  "url": string;
  "active": boolean;
  "events": Array<string>;
  "contentType": "json" | "form";
  "createdAt": string;
};

export type WebhookWrite = {
  "url": string;
  "secret"?: string;
  "events": Array<string>;
  "active"?: boolean;
  "contentType"?: "json" | "form";
};

export type WebhookPage = {
  "items": Array<Webhook>;
  "pageInfo": PageInfo;
};

export type Notification = {
  "id": string;
  "reason": "assign" | "author" | "comment" | "mention" | "review_requested" | "security_alert" | "subscribed" | "team_mention";
  "unread": boolean;
  "subject": SubjectReference;
  "repository": Repository;
  "updatedAt": string;
  "lastReadAt"?: string | null;
};

export type SubjectReference = {
  "kind": "issue" | "pullRequest" | "discussion" | "release" | "workflowRun" | "repository";
  "id": string;
  "title": string;
  "url": string;
};

export type NotificationPage = {
  "items": Array<Notification>;
  "pageInfo": PageInfo;
};

export type SearchResult = RepositorySearchResult | UserSearchResult | IssueSearchResult | CodeSearchResult;

export type RepositorySearchResult = {
  "kind": "repository";
  "score": number;
  "repository": Repository;
};

export type UserSearchResult = {
  "kind": "user";
  "score": number;
  "user": User;
};

export type IssueSearchResult = {
  "kind": "issue" | "pullRequest";
  "score": number;
  "repository": string;
  "issue": Issue | PullRequest;
};

export type CodeSearchResult = {
  "kind": "code";
  "score": number;
  "repository": string;
  "path": string;
  "matches": Array<{
  "line": number;
  "fragment": string;
}>;
};

export type SearchResultPage = {
  "items": Array<SearchResult>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type TimelineEvent = {
  "id": string;
  "kind": "commit" | "create" | "comment" | "stateChange" | "assignment" | "label" | "review" | "merge" | "release";
  "actor": User;
  "subject"?: SubjectReference;
  "createdAt": string;
  "metadata"?: {
  [key: string]: unknown;
};
};

export type getMetaInput = RequestOptions;
export type getMetaOutput = void;

export type getCapabilitiesInput = RequestOptions;
export type getCapabilitiesOutput = void;

export type getViewerInput = RequestOptions;
export type getViewerOutput = void;

export type listAuthMethodsInput = RequestOptions;
export type listAuthMethodsOutput = AuthMethods;

export type startAuthProviderInput = {
  "provider": string;
} & RequestOptions;
export type startAuthProviderOutput = void;

export type completeAuthProviderInput = {
  "provider": string;
} & RequestOptions;
export type completeAuthProviderOutput = void;

export type getSessionInput = RequestOptions;
export type getSessionOutput = void;

export type logoutInput = RequestOptions;
export type logoutOutput = void;

export type loginInput = RequestOptions;
export type loginOutput = void;

export type registerInput = RequestOptions;
export type registerOutput = void;

export type requestPasswordRecoveryInput = RequestOptions;
export type requestPasswordRecoveryOutput = void;

export type resetPasswordInput = {
  "token": string;
} & RequestOptions;
export type resetPasswordOutput = void;

export type getDashboardInput = RequestOptions;
export type getDashboardOutput = Dashboard;

export type getUserInput = {
  "username": string;
} & RequestOptions;
export type getUserOutput = void;

export type listUserRepositoriesInput = {
  "username": string;
} & RequestOptions;
export type listUserRepositoriesOutput = void;

export type listFollowersInput = {
  "username": string;
} & RequestOptions;
export type listFollowersOutput = void;

export type listFollowingInput = {
  "username": string;
} & RequestOptions;
export type listFollowingOutput = void;

export type getOrganizationInput = {
  "org": string;
} & RequestOptions;
export type getOrganizationOutput = Organization;

export type updateOrganizationInput = {
  "org": string;
} & RequestOptions;
export type updateOrganizationOutput = Organization;

export type listTeamsInput = {
  "org": string;
} & RequestOptions;
export type listTeamsOutput = TeamPage;

export type listRepositoriesInput = RequestOptions;
export type listRepositoriesOutput = void;

export type createRepositoryInput = RequestOptions;
export type createRepositoryOutput = void;

export type getRepositoryInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type getRepositoryOutput = void;

export type updateRepositoryInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type updateRepositoryOutput = void;

export type deleteRepositoryInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type deleteRepositoryOutput = void;

export type listRefsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listRefsOutput = RefPage;

export type getTreeInput = {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions;
export type getTreeOutput = GitTree;

export type getBlobInput = {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions;
export type getBlobOutput = GitBlob;

export type getRawContentInput = {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions;
export type getRawContentOutput = void;

export type listCommitsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listCommitsOutput = CommitPage;

export type getCommitInput = {
  "owner": string;
  "repo": string;
  "sha": string;
} & RequestOptions;
export type getCommitOutput = CommitDetail;

export type compareRefsInput = {
  "owner": string;
  "repo": string;
  "base": string;
  "head": string;
} & RequestOptions;
export type compareRefsOutput = Comparison;

export type getBlameInput = {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions;
export type getBlameOutput = Blame;

export type downloadArchiveInput = {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions;
export type downloadArchiveOutput = void;

export type listIssuesInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listIssuesOutput = void;

export type createIssueInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createIssueOutput = void;

export type getIssueInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type getIssueOutput = void;

export type updateIssueInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type updateIssueOutput = void;

export type listIssueCommentsInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type listIssueCommentsOutput = void;

export type createIssueCommentInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type createIssueCommentOutput = void;

export type listLabelsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listLabelsOutput = LabelPage;

export type createLabelInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createLabelOutput = Label;

export type listMilestonesInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listMilestonesOutput = MilestonePage;

export type listPullRequestsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listPullRequestsOutput = void;

export type createPullRequestInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createPullRequestOutput = void;

export type getPullRequestInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type getPullRequestOutput = void;

export type updatePullRequestInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type updatePullRequestOutput = void;

export type listPullRequestFilesInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type listPullRequestFilesOutput = DiffFilePage;

export type listPullRequestReviewsInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type listPullRequestReviewsOutput = ReviewPage;

export type submitPullRequestReviewInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type submitPullRequestReviewOutput = Review;

export type getPullRequestChecksInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type getPullRequestChecksOutput = CheckSuitePage;

export type mergePullRequestInput = {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions;
export type mergePullRequestOutput = MergeResult;

export type listReleasesInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listReleasesOutput = ReleasePage;

export type createReleaseInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createReleaseOutput = Release;

export type listDiscussionsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listDiscussionsOutput = DiscussionPage;

export type createDiscussionInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createDiscussionOutput = Discussion;

export type listWikiPagesInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listWikiPagesOutput = WikiPageList;

export type createWikiPageInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createWikiPageOutput = WikiPage;

export type listProjectsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listProjectsOutput = ProjectPage;

export type createProjectInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createProjectOutput = Project;

export type listWorkflowsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listWorkflowsOutput = WorkflowPage;

export type dispatchWorkflowInput = {
  "owner": string;
  "repo": string;
  "workflowId": string;
} & RequestOptions;
export type dispatchWorkflowOutput = void;

export type listWorkflowRunsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listWorkflowRunsOutput = WorkflowRunPage;

export type getWorkflowRunInput = {
  "owner": string;
  "repo": string;
  "runId": string;
} & RequestOptions;
export type getWorkflowRunOutput = WorkflowRun;

export type cancelWorkflowRunInput = {
  "owner": string;
  "repo": string;
  "runId": string;
} & RequestOptions;
export type cancelWorkflowRunOutput = void;

export type getSecurityOverviewInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type getSecurityOverviewOutput = SecurityOverview;

export type getRepositoryInsightsInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type getRepositoryInsightsOutput = RepositoryInsights;

export type getRepositoryAccessInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type getRepositoryAccessOutput = AccessSettings;

export type replaceRepositoryAccessInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type replaceRepositoryAccessOutput = AccessSettings;

export type getRepositoryCacheInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type getRepositoryCacheOutput = RepositoryCache;

export type updateRepositoryCachePolicyInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type updateRepositoryCachePolicyOutput = RepositoryCache;

export type invalidateRepositoryCacheInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type invalidateRepositoryCacheOutput = CacheInvalidation;

export type listRepositoryRulesInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listRepositoryRulesOutput = RulePage;

export type listWebhooksInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type listWebhooksOutput = WebhookPage;

export type createWebhookInput = {
  "owner": string;
  "repo": string;
} & RequestOptions;
export type createWebhookOutput = Webhook;

export type listNotificationsInput = RequestOptions;
export type listNotificationsOutput = NotificationPage;

export type markNotificationsReadInput = RequestOptions;
export type markNotificationsReadOutput = void;

export type searchInput = RequestOptions;
export type searchOutput = SearchResultPage;

export type streamEventsInput = RequestOptions;
export type streamEventsOutput = void;

export class HubGitClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch = fetch) {}

  private async request<T>(template: string, method: string, input: RequestOptions): Promise<ApiResponse<T>> {
    const path = template.replace(/\{([^}]+)\}/g, (_, key) => encodeURIComponent(String((input as Record<string, unknown>)[key])));
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(input.query ?? {})) if (value !== undefined) query.set(key, String(value));
    const url = new URL(path + (query.size ? `?${query}` : ''), this.baseUrl);
    const response = await this.fetchImpl(url, { method, credentials: input.credentials ?? 'include', headers: { Accept: 'application/json', ...(input.body === undefined ? {} : { 'Content-Type': 'application/json' }), ...input.headers }, body: input.body === undefined ? undefined : JSON.stringify(input.body), signal: input.signal });
    const data = response.status === 204 ? undefined as T : await response.json() as T;
    if (!response.ok) throw Object.assign(new Error(`HubGit request failed with ${response.status}`), { response, data });
    return { data, status: response.status, headers: response.headers };
  }

  async getMeta(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/meta", "GET", input);
  }

  async getCapabilities(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/capabilities", "GET", input);
  }

  async getViewer(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/viewer", "GET", input);
  }

  async listAuthMethods(input: RequestOptions): Promise<ApiResponse<AuthMethods>> {
    return this.request<AuthMethods>("/api/v1/auth/methods", "GET", input);
  }

  async startAuthProvider(input: {
  "provider": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/providers/{provider}/start", "GET", input);
  }

  async completeAuthProvider(input: {
  "provider": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/providers/{provider}/callback", "GET", input);
  }

  async getSession(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/session", "GET", input);
  }

  async logout(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/session", "DELETE", input);
  }

  async login(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/login", "POST", input);
  }

  async register(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/register", "POST", input);
  }

  async requestPasswordRecovery(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/recovery", "POST", input);
  }

  async resetPassword(input: {
  "token": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/auth/recovery/{token}", "POST", input);
  }

  async getDashboard(input: RequestOptions): Promise<ApiResponse<Dashboard>> {
    return this.request<Dashboard>("/api/v1/dashboard", "GET", input);
  }

  async getUser(input: {
  "username": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/users/{username}", "GET", input);
  }

  async listUserRepositories(input: {
  "username": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/users/{username}/repositories", "GET", input);
  }

  async listFollowers(input: {
  "username": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/users/{username}/followers", "GET", input);
  }

  async listFollowing(input: {
  "username": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/users/{username}/following", "GET", input);
  }

  async getOrganization(input: {
  "org": string;
} & RequestOptions): Promise<ApiResponse<Organization>> {
    return this.request<Organization>("/api/v1/organizations/{org}", "GET", input);
  }

  async updateOrganization(input: {
  "org": string;
} & RequestOptions): Promise<ApiResponse<Organization>> {
    return this.request<Organization>("/api/v1/organizations/{org}", "PATCH", input);
  }

  async listTeams(input: {
  "org": string;
} & RequestOptions): Promise<ApiResponse<TeamPage>> {
    return this.request<TeamPage>("/api/v1/organizations/{org}/teams", "GET", input);
  }

  async listRepositories(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories", "GET", input);
  }

  async createRepository(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories", "POST", input);
  }

  async getRepository(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}", "GET", input);
  }

  async updateRepository(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}", "PATCH", input);
  }

  async deleteRepository(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}", "DELETE", input);
  }

  async listRefs(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<RefPage>> {
    return this.request<RefPage>("/api/v1/repositories/{owner}/{repo}/refs", "GET", input);
  }

  async getTree(input: {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions): Promise<ApiResponse<GitTree>> {
    return this.request<GitTree>("/api/v1/repositories/{owner}/{repo}/tree/{ref}", "GET", input);
  }

  async getBlob(input: {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions): Promise<ApiResponse<GitBlob>> {
    return this.request<GitBlob>("/api/v1/repositories/{owner}/{repo}/blob/{ref}", "GET", input);
  }

  async getRawContent(input: {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/raw/{ref}", "GET", input);
  }

  async listCommits(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<CommitPage>> {
    return this.request<CommitPage>("/api/v1/repositories/{owner}/{repo}/commits", "GET", input);
  }

  async getCommit(input: {
  "owner": string;
  "repo": string;
  "sha": string;
} & RequestOptions): Promise<ApiResponse<CommitDetail>> {
    return this.request<CommitDetail>("/api/v1/repositories/{owner}/{repo}/commits/{sha}", "GET", input);
  }

  async compareRefs(input: {
  "owner": string;
  "repo": string;
  "base": string;
  "head": string;
} & RequestOptions): Promise<ApiResponse<Comparison>> {
    return this.request<Comparison>("/api/v1/repositories/{owner}/{repo}/compare/{base}...{head}", "GET", input);
  }

  async getBlame(input: {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions): Promise<ApiResponse<Blame>> {
    return this.request<Blame>("/api/v1/repositories/{owner}/{repo}/blame/{ref}", "GET", input);
  }

  async downloadArchive(input: {
  "owner": string;
  "repo": string;
  "ref": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/archive/{ref}", "GET", input);
  }

  async listIssues(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/issues", "GET", input);
  }

  async createIssue(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/issues", "POST", input);
  }

  async getIssue(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/issues/{number}", "GET", input);
  }

  async updateIssue(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/issues/{number}", "PATCH", input);
  }

  async listIssueComments(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/issues/{number}/comments", "GET", input);
  }

  async createIssueComment(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/issues/{number}/comments", "POST", input);
  }

  async listLabels(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<LabelPage>> {
    return this.request<LabelPage>("/api/v1/repositories/{owner}/{repo}/labels", "GET", input);
  }

  async createLabel(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<Label>> {
    return this.request<Label>("/api/v1/repositories/{owner}/{repo}/labels", "POST", input);
  }

  async listMilestones(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<MilestonePage>> {
    return this.request<MilestonePage>("/api/v1/repositories/{owner}/{repo}/milestones", "GET", input);
  }

  async listPullRequests(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/pulls", "GET", input);
  }

  async createPullRequest(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/pulls", "POST", input);
  }

  async getPullRequest(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/pulls/{number}", "GET", input);
  }

  async updatePullRequest(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/pulls/{number}", "PATCH", input);
  }

  async listPullRequestFiles(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<DiffFilePage>> {
    return this.request<DiffFilePage>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/files", "GET", input);
  }

  async listPullRequestReviews(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<ReviewPage>> {
    return this.request<ReviewPage>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/reviews", "GET", input);
  }

  async submitPullRequestReview(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<Review>> {
    return this.request<Review>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/reviews", "POST", input);
  }

  async getPullRequestChecks(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<CheckSuitePage>> {
    return this.request<CheckSuitePage>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/checks", "GET", input);
  }

  async mergePullRequest(input: {
  "owner": string;
  "repo": string;
  "number": string;
} & RequestOptions): Promise<ApiResponse<MergeResult>> {
    return this.request<MergeResult>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/merge", "POST", input);
  }

  async listReleases(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<ReleasePage>> {
    return this.request<ReleasePage>("/api/v1/repositories/{owner}/{repo}/releases", "GET", input);
  }

  async createRelease(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<Release>> {
    return this.request<Release>("/api/v1/repositories/{owner}/{repo}/releases", "POST", input);
  }

  async listDiscussions(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<DiscussionPage>> {
    return this.request<DiscussionPage>("/api/v1/repositories/{owner}/{repo}/discussions", "GET", input);
  }

  async createDiscussion(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<Discussion>> {
    return this.request<Discussion>("/api/v1/repositories/{owner}/{repo}/discussions", "POST", input);
  }

  async listWikiPages(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<WikiPageList>> {
    return this.request<WikiPageList>("/api/v1/repositories/{owner}/{repo}/wiki/pages", "GET", input);
  }

  async createWikiPage(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<WikiPage>> {
    return this.request<WikiPage>("/api/v1/repositories/{owner}/{repo}/wiki/pages", "POST", input);
  }

  async listProjects(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<ProjectPage>> {
    return this.request<ProjectPage>("/api/v1/repositories/{owner}/{repo}/projects", "GET", input);
  }

  async createProject(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<Project>> {
    return this.request<Project>("/api/v1/repositories/{owner}/{repo}/projects", "POST", input);
  }

  async listWorkflows(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<WorkflowPage>> {
    return this.request<WorkflowPage>("/api/v1/repositories/{owner}/{repo}/workflows", "GET", input);
  }

  async dispatchWorkflow(input: {
  "owner": string;
  "repo": string;
  "workflowId": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/workflows/{workflowId}/dispatch", "POST", input);
  }

  async listWorkflowRuns(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<WorkflowRunPage>> {
    return this.request<WorkflowRunPage>("/api/v1/repositories/{owner}/{repo}/runs", "GET", input);
  }

  async getWorkflowRun(input: {
  "owner": string;
  "repo": string;
  "runId": string;
} & RequestOptions): Promise<ApiResponse<WorkflowRun>> {
    return this.request<WorkflowRun>("/api/v1/repositories/{owner}/{repo}/runs/{runId}", "GET", input);
  }

  async cancelWorkflowRun(input: {
  "owner": string;
  "repo": string;
  "runId": string;
} & RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/repositories/{owner}/{repo}/runs/{runId}", "DELETE", input);
  }

  async getSecurityOverview(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<SecurityOverview>> {
    return this.request<SecurityOverview>("/api/v1/repositories/{owner}/{repo}/security", "GET", input);
  }

  async getRepositoryInsights(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<RepositoryInsights>> {
    return this.request<RepositoryInsights>("/api/v1/repositories/{owner}/{repo}/insights", "GET", input);
  }

  async getRepositoryAccess(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<AccessSettings>> {
    return this.request<AccessSettings>("/api/v1/repositories/{owner}/{repo}/settings/access", "GET", input);
  }

  async replaceRepositoryAccess(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<AccessSettings>> {
    return this.request<AccessSettings>("/api/v1/repositories/{owner}/{repo}/settings/access", "PUT", input);
  }

  async getRepositoryCache(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<RepositoryCache>> {
    return this.request<RepositoryCache>("/api/v1/repositories/{owner}/{repo}/settings/cache", "GET", input);
  }

  async updateRepositoryCachePolicy(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<RepositoryCache>> {
    return this.request<RepositoryCache>("/api/v1/repositories/{owner}/{repo}/settings/cache", "PUT", input);
  }

  async invalidateRepositoryCache(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<CacheInvalidation>> {
    return this.request<CacheInvalidation>("/api/v1/repositories/{owner}/{repo}/settings/cache/invalidate", "POST", input);
  }

  async listRepositoryRules(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<RulePage>> {
    return this.request<RulePage>("/api/v1/repositories/{owner}/{repo}/settings/rules", "GET", input);
  }

  async listWebhooks(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<WebhookPage>> {
    return this.request<WebhookPage>("/api/v1/repositories/{owner}/{repo}/settings/hooks", "GET", input);
  }

  async createWebhook(input: {
  "owner": string;
  "repo": string;
} & RequestOptions): Promise<ApiResponse<Webhook>> {
    return this.request<Webhook>("/api/v1/repositories/{owner}/{repo}/settings/hooks", "POST", input);
  }

  async listNotifications(input: RequestOptions): Promise<ApiResponse<NotificationPage>> {
    return this.request<NotificationPage>("/api/v1/notifications", "GET", input);
  }

  async markNotificationsRead(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/notifications", "PATCH", input);
  }

  async search(input: RequestOptions): Promise<ApiResponse<SearchResultPage>> {
    return this.request<SearchResultPage>("/api/v1/search", "GET", input);
  }

  async streamEvents(input: RequestOptions): Promise<ApiResponse<void>> {
    return this.request<void>("/api/v1/events/stream", "GET", input);
  }
}
