/* eslint-disable */
/**
 * Generated from ../openapi.json by scripts/generate-client.mjs.
 * Do not edit this file directly; run pnpm generate after changing the contract.
 */

export interface RequestControl {
  signal?: AbortSignal;
  credentials?: RequestCredentials;
}

export interface RequestOptions extends RequestControl {
  body?: unknown;
  headers?: Record<string, string>;
  query?: Record<string, string | number | boolean | undefined>;
}

export interface ApiResponse<T> {
  data: T;
  status: number;
  headers: Headers;
}

export class HubGitRequestError extends Error {
  constructor(
    readonly response: Response,
    readonly problem: ProblemDetails | unknown,
  ) {
    super(`HubGit request failed with ${response.status}`);
    this.name = 'HubGitRequestError';
  }
}

export type ProblemDetails = {
  "type": string;
  "title": string;
  "status": number;
  "detail"?: string;
  "instance"?: string;
  "code": string;
  "fieldErrors"?: Array<FieldError>;
  "traceId"?: string;
};

export type FieldError = {
  "field": string;
  "code": string;
  "message": string;
};

export type PageInfo = {
  "startCursor"?: string | null;
  "endCursor"?: string | null;
  "hasNextPage": boolean;
  "hasPreviousPage": boolean;
};

export type ResourcePermissions = {
  "read": boolean;
  "triage"?: boolean;
  "write": boolean;
  "maintain"?: boolean;
  "admin": boolean;
};

export type CapabilitySet = {
  "provider": string;
  "version"?: string;
  "features": {
  "issues": boolean;
  "pullRequests": boolean;
  "releases": boolean;
  "wiki": boolean;
  "discussions": boolean;
  "projects": boolean;
  "actions": boolean;
  "security": boolean;
  "insights": boolean;
  "webhooks"?: boolean;
  "repositoryRules"?: boolean;
  "serverSentEvents"?: boolean;
};
  "limits"?: {
  "maxPageSize"?: number;
  "maxUploadBytes"?: number;
};
};

export type Freshness = {
  "state": "live" | "refreshing" | "stale" | "offline";
  "lastSyncedAt": string | null;
  "lastAuthorizedAt": string | null;
  "provider": string;
};

export type BrandingManifest = {
  "preset": string;
  "productName": string;
  "shortName": string;
  "logoUrl": string | null;
  "faviconUrl": string | null;
  "titleTemplate": string;
  "colors": {
  "accent": string;
  "headerBackground": string;
  [key: string]: string;
};
  "authentication": {
  "heading": string;
  "description": string;
  "connectLabel": string;
};
  "links": {
  "privacy": string | null;
  "terms": string | null;
  "source": string | null;
  "support": string | null;
};
  "notice": string | null;
  "providerDisplayNames": {
  [key: string]: string;
};
};

export type InstanceMeta = {
  "name": string;
  "baseUrl": string;
  "branding": BrandingManifest;
  "registrationEnabled": boolean;
  "version"?: string;
  "freshness"?: Freshness;
};

export type AuthProvider = {
  "id": string;
  "displayName": string;
  "enabled": boolean;
  "supportsRegistration"?: boolean;
};

export type AuthMethods = {
  "password": boolean;
  "passkey": boolean;
  "twoFactor": boolean;
  "providers": Array<AuthProvider>;
};

export type LoginRequest = {
  "login": string;
  "password": string;
  "otp"?: string;
  "remember"?: boolean;
};

export type RegisterRequest = {
  "username": string;
  "email": string;
  "password": string;
};

export type Session = {
  "authenticated": boolean;
  "csrfToken": string;
  "expiresAt": string | null;
  "viewer": Viewer | null;
};

export type Viewer = User & {
  "roles": Array<"member" | "maintainer" | "administrator">;
  "email"?: string;
  "unreadNotificationCount"?: number;
};

export type User = {
  "id": string;
  "kind": "user";
  "username": string;
  "displayName": string;
  "avatarUrl": string;
  "profileUrl": string;
  "bio"?: string | null;
  "location"?: string | null;
  "followerCount"?: number;
  "followingCount"?: number;
  "createdAt"?: string;
  "freshness"?: Freshness;
};

export type UserPage = {
  "items": Array<User>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type Organization = {
  "id": string;
  "kind": "organization";
  "login": string;
  "displayName": string;
  "description"?: string | null;
  "avatarUrl": string;
  "websiteUrl"?: string | null;
  "permissions": ResourcePermissions;
};

export type OrganizationUpdate = {
  "displayName"?: string;
  "description"?: string | null;
  "websiteUrl"?: string | null;
};

export type Team = {
  "id": string;
  "name": string;
  "slug": string;
  "permission": "read" | "triage" | "write" | "maintain" | "admin";
  "memberCount": number;
};

export type TeamPage = {
  "items": Array<Team>;
  "pageInfo": PageInfo;
};

export type Repository = {
  "id": string;
  "kind": "repository";
  "owner": RepositoryOwner;
  "name": string;
  "fullName": string;
  "description"?: string | null;
  "visibility": "public" | "internal" | "private";
  "defaultBranch": string;
  "empty": boolean;
  "archived": boolean;
  "fork"?: boolean;
  "forkedFrom"?: string | null;
  "language"?: string | null;
  "license"?: string | null;
  "topics"?: Array<string>;
  "permissions": ResourcePermissions;
  "counts": RepositoryCounts;
  "cloneUrls": CloneUrls;
  "createdAt": string;
  "updatedAt": string;
  "pushedAt"?: string | null;
  "freshness"?: Freshness;
};

export type RepositoryOwner = {
  "id": string;
  "kind": "user" | "organization";
  "login": string;
  "avatarUrl": string;
};

export type RepositoryCounts = {
  "stars": number;
  "forks": number;
  "watchers": number;
  "issues": number;
  "pullRequests": number;
};

export type CloneUrls = {
  "http": string;
  "ssh": string;
};

export type RepositoryCreate = {
  "owner": string;
  "name": string;
  "description"?: string | null;
  "visibility": "public" | "internal" | "private";
  "initialize"?: boolean;
};

export type RepositoryUpdate = {
  "name"?: string;
  "description"?: string | null;
  "visibility"?: "public" | "internal" | "private";
  "defaultBranch"?: string;
  "archived"?: boolean;
  "features"?: RepositoryFeatures;
};

export type RepositoryFeatures = {
  "issues"?: boolean;
  "wiki"?: boolean;
  "discussions"?: boolean;
  "projects"?: boolean;
};

export type RepositoryPage = {
  "items": Array<Repository>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type Dashboard = {
  "repositories": RepositoryPage;
  "activity": Array<TimelineEvent>;
};

export type GitRef = {
  "name": string;
  "kind": "branch" | "tag";
  "sha": string;
  "protected": boolean;
  "aheadBy"?: number;
  "behindBy"?: number;
};

export type RefPage = {
  "items": Array<GitRef>;
  "pageInfo": PageInfo;
};

export type GitTree = {
  "sha": string;
  "ref": string;
  "path": string;
  "entries": Array<TreeEntry>;
  "commit": CommitSummary;
};

export type TreeEntry = {
  "name": string;
  "path": string;
  "kind": "file" | "directory" | "symlink" | "submodule";
  "sha": string;
  "size"?: number | null;
  "lastCommit"?: CommitSummary;
};

export type GitBlob = {
  "sha": string;
  "path": string;
  "size": number;
  "binary": boolean;
  "truncated": boolean;
  "encoding": "utf-8" | "base64";
  "content"?: string | null;
  "language"?: string | null;
  "lfs"?: boolean;
};

export type CommitSummary = {
  "sha": string;
  "shortSha": string;
  "message": string;
  "author": GitActor;
  "authoredAt": string;
  "verification"?: Verification;
};

export type GitActor = {
  "name": string;
  "email": string;
  "user"?: User | null;
};

export type Verification = {
  "verified": boolean;
  "reason"?: string | null;
  "signatureType"?: "gpg" | "ssh" | "smime" | null;
};

export type CommitDetail = CommitSummary & {
  "parents": Array<string>;
  "committer": GitActor;
  "committedAt": string;
  "body"?: string;
  "stats": DiffStats;
  "files": Array<DiffFile>;
};

export type CommitPage = {
  "items": Array<CommitSummary>;
  "pageInfo": PageInfo;
};

export type DiffStats = {
  "additions": number;
  "deletions": number;
  "filesChanged": number;
};

export type DiffFile = {
  "oldPath": string | null;
  "newPath": string | null;
  "status": "added" | "modified" | "deleted" | "renamed" | "copied";
  "binary": boolean;
  "additions": number;
  "deletions": number;
  "hunks": Array<DiffHunk>;
};

export type DiffHunk = {
  "header": string;
  "lines": Array<DiffLine>;
};

export type DiffLine = {
  "kind": "context" | "addition" | "deletion" | "no-newline";
  "oldLine"?: number | null;
  "newLine"?: number | null;
  "content": string;
};

export type DiffFilePage = {
  "items": Array<DiffFile>;
  "pageInfo": PageInfo;
};

export type Comparison = {
  "status": "identical" | "ahead" | "behind" | "diverged";
  "aheadBy": number;
  "behindBy": number;
  "mergeBaseSha"?: string | null;
  "commits": Array<CommitSummary>;
  "files": Array<DiffFile>;
  "stats": DiffStats;
};

export type Blame = {
  "path": string;
  "ranges": Array<{
  "startLine": number;
  "endLine": number;
  "commit": CommitSummary;
}>;
};

export type Label = {
  "id": string;
  "name": string;
  "color": string;
  "description": string;
};

export type LabelWrite = {
  "name": string;
  "color": string;
  "description"?: string;
};

export type LabelPage = {
  "items": Array<Label>;
  "pageInfo": PageInfo;
};

export type Milestone = {
  "id": string;
  "number": number;
  "title": string;
  "description"?: string | null;
  "state": "open" | "closed";
  "dueAt"?: string | null;
  "openIssueCount": number;
  "closedIssueCount": number;
};

export type MilestonePage = {
  "items": Array<Milestone>;
  "pageInfo": PageInfo;
};

export type Issue = {
  "id": string;
  "kind": "issue";
  "number": number;
  "title": string;
  "body": string;
  "state": "open" | "closed";
  "stateReason"?: "completed" | "not_planned" | "reopened" | null;
  "author": User;
  "labels": Array<Label>;
  "assignees": Array<User>;
  "milestone"?: Milestone | null;
  "commentCount": number;
  "permissions": ResourcePermissions;
  "createdAt": string;
  "updatedAt": string;
  "closedAt"?: string | null;
  "freshness"?: Freshness;
};

export type IssueWrite = {
  "title"?: string;
  "body"?: string;
  "state"?: "open" | "closed";
  "stateReason"?: "completed" | "not_planned" | "reopened" | null;
  "labelIds"?: Array<string>;
  "assigneeIds"?: Array<string>;
  "milestoneId"?: string | null;
};

export type IssuePage = {
  "items": Array<Issue>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type Comment = {
  "id": string;
  "body": string;
  "author": User;
  "reactions": Array<ReactionGroup>;
  "permissions": ResourcePermissions;
  "createdAt": string;
  "updatedAt": string;
};

export type CommentWrite = {
  "body": string;
};

export type CommentPage = {
  "items": Array<Comment>;
  "pageInfo": PageInfo;
};

export type ReactionGroup = {
  "content": "+1" | "-1" | "laugh" | "hooray" | "confused" | "heart" | "rocket" | "eyes";
  "count": number;
  "viewerHasReacted": boolean;
};

export type PullRequest = {
  "id": string;
  "kind": "pullRequest";
  "number": number;
  "title": string;
  "body": string;
  "state": "open" | "closed" | "merged";
  "draft": boolean;
  "author": User;
  "base": PullRequestRef;
  "head": PullRequestRef;
  "mergeability": "mergeable" | "conflicting" | "checking" | "blocked" | "unknown";
  "reviewDecision": "approved" | "changes_requested" | "review_required" | "none";
  "checks": CheckSummary;
  "labels"?: Array<Label>;
  "permissions": ResourcePermissions;
  "createdAt": string;
  "updatedAt": string;
  "mergedAt"?: string | null;
  "freshness"?: Freshness;
};

export type PullRequestRef = {
  "repository": string;
  "ref": string;
  "sha": string;
};

export type PullRequestCreate = {
  "title": string;
  "body"?: string;
  "head": string;
  "base": string;
  "draft"?: boolean;
};

export type PullRequestPage = {
  "items": Array<PullRequest>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type CheckSummary = {
  "total": number;
  "queued": number;
  "inProgress": number;
  "successful": number;
  "failed": number;
};

export type CheckSuite = {
  "id": string;
  "name": string;
  "status": "queued" | "in_progress" | "completed";
  "conclusion": "success" | "failure" | "neutral" | "cancelled" | "skipped" | "timed_out" | null;
  "checks": Array<CheckRun>;
  "startedAt": string;
  "completedAt"?: string | null;
};

export type CheckRun = {
  "id": string;
  "name": string;
  "status": "queued" | "in_progress" | "completed";
  "conclusion": string | null;
  "detailsUrl"?: string | null;
  "summary"?: string | null;
};

export type CheckSuitePage = {
  "items": Array<CheckSuite>;
  "pageInfo": PageInfo;
};

export type Review = {
  "id": string;
  "author": User;
  "state": "commented" | "approved" | "changes_requested" | "dismissed" | "pending";
  "body": string;
  "commitSha"?: string;
  "submittedAt": string;
};

export type ReviewWrite = {
  "event": "comment" | "approve" | "request_changes";
  "body"?: string;
  "comments"?: Array<{
  "path": string;
  "line": number;
  "side"?: "left" | "right";
  "body": string;
}>;
};

export type ReviewPage = {
  "items": Array<Review>;
  "pageInfo": PageInfo;
};

export type MergeRequest = {
  "method": "merge" | "squash" | "rebase";
  "title"?: string;
  "message"?: string;
  "expectedHeadSha": string;
};

export type MergeResult = {
  "merged": boolean;
  "sha": string | null;
  "message": string;
};

export type Release = {
  "id": string;
  "tagName": string;
  "name": string;
  "body": string;
  "draft": boolean;
  "prerelease": boolean;
  "author": User;
  "assets": Array<ReleaseAsset>;
  "createdAt": string;
  "publishedAt"?: string | null;
};

export type ReleaseAsset = {
  "id": string;
  "name": string;
  "size": number;
  "contentType"?: string;
  "downloadUrl": string;
  "downloadCount": number;
};

export type ReleaseWrite = {
  "tagName": string;
  "target"?: string;
  "name": string;
  "body"?: string;
  "draft"?: boolean;
  "prerelease"?: boolean;
};

export type ReleasePage = {
  "items": Array<Release>;
  "pageInfo": PageInfo;
};

export type Discussion = {
  "id": string;
  "number": number;
  "title": string;
  "body": string;
  "category": DiscussionCategory;
  "author": User;
  "answered": boolean;
  "commentCount": number;
  "createdAt": string;
};

export type DiscussionCategory = {
  "id": string;
  "name": string;
  "slug": string;
  "emoji": string;
  "answerable"?: boolean;
};

export type DiscussionWrite = {
  "title": string;
  "body": string;
  "categoryId": string;
};

export type DiscussionPage = {
  "items": Array<Discussion>;
  "pageInfo": PageInfo;
};

export type WikiPage = {
  "id": string;
  "slug": string;
  "title": string;
  "body": string;
  "sha": string;
  "updatedAt": string;
};

export type WikiWrite = {
  "title": string;
  "body": string;
  "message"?: string;
};

export type WikiPageList = {
  "items": Array<WikiPage>;
  "cloneUrl"?: string;
};

export type Project = {
  "id": string;
  "title": string;
  "description": string;
  "closed": boolean;
  "views": Array<ProjectView>;
  "itemCount": number;
};

export type ProjectView = {
  "id": string;
  "name": string;
  "layout": "table" | "board";
};

export type ProjectWrite = {
  "title": string;
  "description"?: string;
};

export type ProjectPage = {
  "items": Array<Project>;
  "pageInfo": PageInfo;
};

export type Workflow = {
  "id": string;
  "name": string;
  "path": string;
  "state": "active" | "disabled";
};

export type WorkflowPage = {
  "items": Array<Workflow>;
  "pageInfo": PageInfo;
};

export type WorkflowDispatch = {
  "ref": string;
  "inputs"?: {
  [key: string]: string;
};
};

export type WorkflowRun = {
  "id": string;
  "name": string;
  "event": string;
  "status": "queued" | "in_progress" | "completed";
  "conclusion": string | null;
  "headSha": string;
  "jobs": Array<WorkflowJob>;
  "createdAt": string;
};

export type WorkflowJob = {
  "id": string;
  "name": string;
  "status": string;
  "conclusion": string | null;
  "steps": Array<{
  "name": string;
  "status": string;
  "conclusion"?: string | null;
}>;
  "logUrl"?: string | null;
};

export type WorkflowRunPage = {
  "items": Array<WorkflowRun>;
  "pageInfo": PageInfo;
};

export type SecurityOverview = {
  "policyEnabled": boolean;
  "dependencyAlerts": number;
  "codeScanningAlerts": number;
  "secretScanningAlerts": number;
};

export type RepositoryInsights = {
  "period": string;
  "commits": Array<TimeSeriesPoint>;
  "contributors": Array<ContributorStats>;
  "traffic": Array<TimeSeriesPoint>;
};

export type TimeSeriesPoint = {
  "at": string;
  "value": number;
};

export type ContributorStats = {
  "user": User;
  "commits": number;
  "additions": number;
  "deletions": number;
};

export type RepositoryCachePolicy = {
  "mode": "disabled" | "private" | "shared";
  "maxAgeSeconds": number;
  "staleWhileRevalidateSeconds"?: number;
};

export type RepositoryCacheStatus = {
  "state": "cold" | "warm" | "refreshing" | "error";
  "lastInvalidatedAt": string | null;
  "entryCount": number;
  "lastErrorCode"?: string | null;
};

export type RepositoryCache = {
  "policy": RepositoryCachePolicy;
  "status": RepositoryCacheStatus;
  "freshness": Freshness;
};

export type CacheInvalidation = {
  "accepted": true;
  "requestedAt": string;
  "topics"?: Array<string>;
};

export type AccessSettings = {
  "collaborators": Array<AccessGrant>;
  "teams": Array<AccessGrant>;
  "freshness"?: Freshness;
};

export type AccessGrant = {
  "subjectId": string;
  "subjectKind": "user" | "team";
  "permission": "read" | "triage" | "write" | "maintain" | "admin";
};

export type RepositoryRule = {
  "id": string;
  "name": string;
  "target": "branch" | "tag";
  "enforcement": "active" | "disabled" | "evaluate";
  "rules": Array<{
  "kind": string;
  "parameters"?: {
  [key: string]: unknown;
};
}>;
};

export type RulePage = {
  "items": Array<RepositoryRule>;
  "pageInfo": PageInfo;
};

export type Webhook = {
  "id": string;
  "url": string;
  "active": boolean;
  "events": Array<string>;
  "contentType": "json" | "form";
  "createdAt": string;
};

export type WebhookWrite = {
  "url": string;
  "secret"?: string;
  "events": Array<string>;
  "active"?: boolean;
  "contentType"?: "json" | "form";
};

export type WebhookPage = {
  "items": Array<Webhook>;
  "pageInfo": PageInfo;
};

export type Notification = {
  "id": string;
  "reason": "assign" | "author" | "comment" | "mention" | "review_requested" | "security_alert" | "subscribed" | "team_mention";
  "unread": boolean;
  "subject": SubjectReference;
  "repository": Repository;
  "updatedAt": string;
  "lastReadAt"?: string | null;
};

export type SubjectReference = {
  "kind": "issue" | "pullRequest" | "discussion" | "release" | "workflowRun" | "repository";
  "id": string;
  "title": string;
  "url": string;
};

export type NotificationPage = {
  "items": Array<Notification>;
  "pageInfo": PageInfo;
};

export type SearchResult = RepositorySearchResult | UserSearchResult | IssueSearchResult | CodeSearchResult;

export type RepositorySearchResult = {
  "kind": "repository";
  "score": number;
  "repository": Repository;
};

export type UserSearchResult = {
  "kind": "user";
  "score": number;
  "user": User;
};

export type IssueSearchResult = {
  "kind": "issue" | "pullRequest";
  "score": number;
  "repository": string;
  "issue": Issue | PullRequest;
};

export type CodeSearchResult = {
  "kind": "code";
  "score": number;
  "repository": string;
  "path": string;
  "matches": Array<{
  "line": number;
  "fragment": string;
}>;
};

export type SearchResultPage = {
  "items": Array<SearchResult>;
  "pageInfo": PageInfo;
  "totalCount"?: number;
};

export type TimelineEvent = {
  "id": string;
  "kind": "commit" | "create" | "comment" | "stateChange" | "assignment" | "label" | "review" | "merge" | "release";
  "actor": User;
  "subject"?: SubjectReference;
  "createdAt": string;
  "metadata"?: {
  [key: string]: unknown;
};
};

export type getMetaInput = RequestControl;
export type getMetaOutput = InstanceMeta;

export type getCapabilitiesInput = RequestControl;
export type getCapabilitiesOutput = CapabilitySet;

export type getViewerInput = RequestControl;
export type getViewerOutput = Viewer;

export type listAuthMethodsInput = RequestControl;
export type listAuthMethodsOutput = AuthMethods;

export type startAuthProviderInput = {
  "provider": string;
  query?: {
    "redirectUri"?: string;
  };
} & RequestControl;
export type startAuthProviderOutput = void;

export type completeAuthProviderInput = {
  "provider": string;
  query?: {
    "code"?: string;
    "state"?: string;
    "error"?: string;
    "errorDescription"?: string;
  };
} & RequestControl;
export type completeAuthProviderOutput = Session;

export type getSessionInput = RequestControl;
export type getSessionOutput = Session;

export type logoutInput = {
  headers: {
    "X-CSRF-Token": string;
  };
} & RequestControl;
export type logoutOutput = void;

export type loginInput = {
  body: LoginRequest;
} & RequestControl;
export type loginOutput = Session;

export type registerInput = {
  body: RegisterRequest;
} & RequestControl;
export type registerOutput = Session;

export type requestPasswordRecoveryInput = {
  body: {
  "email": string;
};
} & RequestControl;
export type requestPasswordRecoveryOutput = void;

export type resetPasswordInput = {
  "token": string;
  body: {
  "password": string;
};
} & RequestControl;
export type resetPasswordOutput = void;

export type getDashboardInput = {
  query?: {
    "cursor"?: string;
    "limit"?: number;
  };
} & RequestControl;
export type getDashboardOutput = Dashboard;

export type getUserInput = {
  "username": string;
} & RequestControl;
export type getUserOutput = User;

export type listUserRepositoriesInput = {
  "username": string;
  query?: {
    "cursor"?: string;
    "limit"?: number;
  };
} & RequestControl;
export type listUserRepositoriesOutput = RepositoryPage;

export type listFollowersInput = {
  "username": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listFollowersOutput = UserPage;

export type listFollowingInput = {
  "username": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listFollowingOutput = UserPage;

export type getOrganizationInput = {
  "org": string;
} & RequestControl;
export type getOrganizationOutput = Organization;

export type updateOrganizationInput = {
  "org": string;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
  body: OrganizationUpdate;
} & RequestControl;
export type updateOrganizationOutput = Organization;

export type listTeamsInput = {
  "org": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listTeamsOutput = TeamPage;

export type listRepositoriesInput = {
  query?: {
    "cursor"?: string;
    "limit"?: number;
    "q"?: string;
  };
} & RequestControl;
export type listRepositoriesOutput = RepositoryPage;

export type createRepositoryInput = {
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: RepositoryCreate;
} & RequestControl;
export type createRepositoryOutput = Repository;

export type getRepositoryInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type getRepositoryOutput = Repository;

export type updateRepositoryInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
  body: RepositoryUpdate;
} & RequestControl;
export type updateRepositoryOutput = Repository;

export type deleteRepositoryInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
} & RequestControl;
export type deleteRepositoryOutput = void;

export type listRefsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "kind"?: "branch" | "tag";
    "cursor"?: string;
  };
} & RequestControl;
export type listRefsOutput = RefPage;

export type getTreeInput = {
  "owner": string;
  "repo": string;
  "ref": string;
  query?: {
    "path"?: string;
  };
} & RequestControl;
export type getTreeOutput = GitTree;

export type getBlobInput = {
  "owner": string;
  "repo": string;
  "ref": string;
  query?: {
    "path"?: string;
  };
} & RequestControl;
export type getBlobOutput = GitBlob;

export type getRawContentInput = {
  "owner": string;
  "repo": string;
  "ref": string;
  query?: {
    "path"?: string;
  };
} & RequestControl;
export type getRawContentOutput = string;

export type listCommitsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "ref"?: string;
    "path"?: string;
    "cursor"?: string;
  };
} & RequestControl;
export type listCommitsOutput = CommitPage;

export type getCommitInput = {
  "owner": string;
  "repo": string;
  "sha": string;
} & RequestControl;
export type getCommitOutput = CommitDetail;

export type compareRefsInput = {
  "owner": string;
  "repo": string;
  "base": string;
  "head": string;
} & RequestControl;
export type compareRefsOutput = Comparison;

export type getBlameInput = {
  "owner": string;
  "repo": string;
  "ref": string;
  query?: {
    "path"?: string;
  };
} & RequestControl;
export type getBlameOutput = Blame;

export type downloadArchiveInput = {
  "owner": string;
  "repo": string;
  "ref": string;
  query?: {
    "format"?: "zip" | "tar.gz";
  };
} & RequestControl;
export type downloadArchiveOutput = string;

export type listIssuesInput = {
  "owner": string;
  "repo": string;
  query?: {
    "state"?: "open" | "closed" | "all";
    "q"?: string;
    "cursor"?: string;
  };
} & RequestControl;
export type listIssuesOutput = IssuePage;

export type createIssueInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: IssueWrite;
} & RequestControl;
export type createIssueOutput = Issue;

export type getIssueInput = {
  "owner": string;
  "repo": string;
  "number": number;
} & RequestControl;
export type getIssueOutput = Issue;

export type updateIssueInput = {
  "owner": string;
  "repo": string;
  "number": number;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
  body: IssueWrite;
} & RequestControl;
export type updateIssueOutput = Issue;

export type listIssueCommentsInput = {
  "owner": string;
  "repo": string;
  "number": number;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listIssueCommentsOutput = CommentPage;

export type createIssueCommentInput = {
  "owner": string;
  "repo": string;
  "number": number;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: CommentWrite;
} & RequestControl;
export type createIssueCommentOutput = Comment;

export type listLabelsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listLabelsOutput = LabelPage;

export type createLabelInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: LabelWrite;
} & RequestControl;
export type createLabelOutput = Label;

export type listMilestonesInput = {
  "owner": string;
  "repo": string;
  query?: {
    "state"?: "open" | "closed" | "all";
  };
} & RequestControl;
export type listMilestonesOutput = MilestonePage;

export type listPullRequestsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "state"?: "open" | "closed" | "all";
    "cursor"?: string;
  };
} & RequestControl;
export type listPullRequestsOutput = PullRequestPage;

export type createPullRequestInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: PullRequestCreate;
} & RequestControl;
export type createPullRequestOutput = PullRequest;

export type getPullRequestInput = {
  "owner": string;
  "repo": string;
  "number": number;
} & RequestControl;
export type getPullRequestOutput = PullRequest;

export type updatePullRequestInput = {
  "owner": string;
  "repo": string;
  "number": number;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
  body: IssueWrite;
} & RequestControl;
export type updatePullRequestOutput = PullRequest;

export type listPullRequestFilesInput = {
  "owner": string;
  "repo": string;
  "number": number;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listPullRequestFilesOutput = DiffFilePage;

export type listPullRequestReviewsInput = {
  "owner": string;
  "repo": string;
  "number": number;
} & RequestControl;
export type listPullRequestReviewsOutput = ReviewPage;

export type submitPullRequestReviewInput = {
  "owner": string;
  "repo": string;
  "number": number;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: ReviewWrite;
} & RequestControl;
export type submitPullRequestReviewOutput = Review;

export type getPullRequestChecksInput = {
  "owner": string;
  "repo": string;
  "number": number;
} & RequestControl;
export type getPullRequestChecksOutput = CheckSuitePage;

export type mergePullRequestInput = {
  "owner": string;
  "repo": string;
  "number": number;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: MergeRequest;
} & RequestControl;
export type mergePullRequestOutput = MergeResult;

export type listReleasesInput = {
  "owner": string;
  "repo": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listReleasesOutput = ReleasePage;

export type createReleaseInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: ReleaseWrite;
} & RequestControl;
export type createReleaseOutput = Release;

export type listDiscussionsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listDiscussionsOutput = DiscussionPage;

export type createDiscussionInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: DiscussionWrite;
} & RequestControl;
export type createDiscussionOutput = Discussion;

export type listWikiPagesInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type listWikiPagesOutput = WikiPageList;

export type createWikiPageInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: WikiWrite;
} & RequestControl;
export type createWikiPageOutput = WikiPage;

export type listProjectsInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type listProjectsOutput = ProjectPage;

export type createProjectInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: ProjectWrite;
} & RequestControl;
export type createProjectOutput = Project;

export type listWorkflowsInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type listWorkflowsOutput = WorkflowPage;

export type dispatchWorkflowInput = {
  "owner": string;
  "repo": string;
  "workflowId": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: WorkflowDispatch;
} & RequestControl;
export type dispatchWorkflowOutput = void;

export type listWorkflowRunsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "cursor"?: string;
  };
} & RequestControl;
export type listWorkflowRunsOutput = WorkflowRunPage;

export type getWorkflowRunInput = {
  "owner": string;
  "repo": string;
  "runId": string;
} & RequestControl;
export type getWorkflowRunOutput = WorkflowRun;

export type cancelWorkflowRunInput = {
  "owner": string;
  "repo": string;
  "runId": string;
  headers: {
    "X-CSRF-Token": string;
  };
} & RequestControl;
export type cancelWorkflowRunOutput = void;

export type getSecurityOverviewInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type getSecurityOverviewOutput = SecurityOverview;

export type getRepositoryInsightsInput = {
  "owner": string;
  "repo": string;
  query?: {
    "period"?: "week" | "month" | "year";
  };
} & RequestControl;
export type getRepositoryInsightsOutput = RepositoryInsights;

export type getRepositoryAccessInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type getRepositoryAccessOutput = AccessSettings;

export type replaceRepositoryAccessInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
  body: AccessSettings;
} & RequestControl;
export type replaceRepositoryAccessOutput = AccessSettings;

export type getRepositoryCacheInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type getRepositoryCacheOutput = RepositoryCache;

export type updateRepositoryCachePolicyInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "If-Match": string;
  };
  body: RepositoryCachePolicy;
} & RequestControl;
export type updateRepositoryCachePolicyOutput = RepositoryCache;

export type invalidateRepositoryCacheInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
} & RequestControl;
export type invalidateRepositoryCacheOutput = CacheInvalidation;

export type listRepositoryRulesInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type listRepositoryRulesOutput = RulePage;

export type listWebhooksInput = {
  "owner": string;
  "repo": string;
} & RequestControl;
export type listWebhooksOutput = WebhookPage;

export type createWebhookInput = {
  "owner": string;
  "repo": string;
  headers: {
    "X-CSRF-Token": string;
    "Idempotency-Key": string;
  };
  body: WebhookWrite;
} & RequestControl;
export type createWebhookOutput = Webhook;

export type listNotificationsInput = {
  query?: {
    "cursor"?: string;
    "unread"?: boolean;
  };
} & RequestControl;
export type listNotificationsOutput = NotificationPage;

export type markNotificationsReadInput = {
  headers: {
    "X-CSRF-Token": string;
  };
  body: {
  "ids"?: Array<string>;
  "all"?: boolean;
};
} & RequestControl;
export type markNotificationsReadOutput = void;

export type searchInput = {
  query: {
    "q": string;
    "type"?: "repositories" | "code" | "commits" | "issues" | "pulls" | "discussions" | "users" | "organizations";
    "cursor"?: string;
  };
} & RequestControl;
export type searchOutput = SearchResultPage;

export type streamEventsInput = RequestControl;
export type streamEventsOutput = string;

export class HubGitClient {
  constructor(private readonly baseUrl: string, private readonly fetchImpl: typeof fetch = fetch) {}

  private async request<T>(template: string, method: string, input: RequestOptions, contentType = 'application/json'): Promise<ApiResponse<T>> {
    const path = template.replace(/\{([^}]+)\}/g, (_, key) => encodeURIComponent(String((input as Record<string, unknown>)[key])));
    const query = new URLSearchParams();
    for (const [key, value] of Object.entries(input.query ?? {})) if (value !== undefined) query.set(key, String(value));
    const url = new URL(path + (query.size ? `?${query}` : ''), this.baseUrl);
    const response = await this.fetchImpl(url, { method, credentials: input.credentials ?? 'include', headers: { Accept: 'application/json', ...(input.body === undefined ? {} : { 'Content-Type': contentType }), ...input.headers }, body: input.body === undefined ? undefined : JSON.stringify(input.body), signal: input.signal });
    const responseContentType = response.headers.get('content-type') ?? '';
    const data = response.status === 204 ? undefined as T : responseContentType.includes('json') ? await response.json() as T : await response.text() as T;
    if (!response.ok) throw new HubGitRequestError(response, data);
    return { data, status: response.status, headers: response.headers };
  }

  async getMeta(input: getMetaInput): Promise<ApiResponse<getMetaOutput>> {
    return this.request<getMetaOutput>("/api/v1/meta", "GET", input);
  }

  async getCapabilities(input: getCapabilitiesInput): Promise<ApiResponse<getCapabilitiesOutput>> {
    return this.request<getCapabilitiesOutput>("/api/v1/capabilities", "GET", input);
  }

  async getViewer(input: getViewerInput): Promise<ApiResponse<getViewerOutput>> {
    return this.request<getViewerOutput>("/api/v1/viewer", "GET", input);
  }

  async listAuthMethods(input: listAuthMethodsInput): Promise<ApiResponse<listAuthMethodsOutput>> {
    return this.request<listAuthMethodsOutput>("/api/v1/auth/methods", "GET", input);
  }

  async startAuthProvider(input: startAuthProviderInput): Promise<ApiResponse<startAuthProviderOutput>> {
    return this.request<startAuthProviderOutput>("/api/v1/auth/providers/{provider}/start", "GET", input);
  }

  async completeAuthProvider(input: completeAuthProviderInput): Promise<ApiResponse<completeAuthProviderOutput>> {
    return this.request<completeAuthProviderOutput>("/api/v1/auth/providers/{provider}/callback", "GET", input);
  }

  async getSession(input: getSessionInput): Promise<ApiResponse<getSessionOutput>> {
    return this.request<getSessionOutput>("/api/v1/auth/session", "GET", input);
  }

  async logout(input: logoutInput): Promise<ApiResponse<logoutOutput>> {
    return this.request<logoutOutput>("/api/v1/auth/session", "DELETE", input);
  }

  async login(input: loginInput): Promise<ApiResponse<loginOutput>> {
    return this.request<loginOutput>("/api/v1/auth/login", "POST", input, "application/json");
  }

  async register(input: registerInput): Promise<ApiResponse<registerOutput>> {
    return this.request<registerOutput>("/api/v1/auth/register", "POST", input, "application/json");
  }

  async requestPasswordRecovery(input: requestPasswordRecoveryInput): Promise<ApiResponse<requestPasswordRecoveryOutput>> {
    return this.request<requestPasswordRecoveryOutput>("/api/v1/auth/recovery", "POST", input, "application/json");
  }

  async resetPassword(input: resetPasswordInput): Promise<ApiResponse<resetPasswordOutput>> {
    return this.request<resetPasswordOutput>("/api/v1/auth/recovery/{token}", "POST", input, "application/json");
  }

  async getDashboard(input: getDashboardInput): Promise<ApiResponse<getDashboardOutput>> {
    return this.request<getDashboardOutput>("/api/v1/dashboard", "GET", input);
  }

  async getUser(input: getUserInput): Promise<ApiResponse<getUserOutput>> {
    return this.request<getUserOutput>("/api/v1/users/{username}", "GET", input);
  }

  async listUserRepositories(input: listUserRepositoriesInput): Promise<ApiResponse<listUserRepositoriesOutput>> {
    return this.request<listUserRepositoriesOutput>("/api/v1/users/{username}/repositories", "GET", input);
  }

  async listFollowers(input: listFollowersInput): Promise<ApiResponse<listFollowersOutput>> {
    return this.request<listFollowersOutput>("/api/v1/users/{username}/followers", "GET", input);
  }

  async listFollowing(input: listFollowingInput): Promise<ApiResponse<listFollowingOutput>> {
    return this.request<listFollowingOutput>("/api/v1/users/{username}/following", "GET", input);
  }

  async getOrganization(input: getOrganizationInput): Promise<ApiResponse<getOrganizationOutput>> {
    return this.request<getOrganizationOutput>("/api/v1/organizations/{org}", "GET", input);
  }

  async updateOrganization(input: updateOrganizationInput): Promise<ApiResponse<updateOrganizationOutput>> {
    return this.request<updateOrganizationOutput>("/api/v1/organizations/{org}", "PATCH", input, "application/merge-patch+json");
  }

  async listTeams(input: listTeamsInput): Promise<ApiResponse<listTeamsOutput>> {
    return this.request<listTeamsOutput>("/api/v1/organizations/{org}/teams", "GET", input);
  }

  async listRepositories(input: listRepositoriesInput): Promise<ApiResponse<listRepositoriesOutput>> {
    return this.request<listRepositoriesOutput>("/api/v1/repositories", "GET", input);
  }

  async createRepository(input: createRepositoryInput): Promise<ApiResponse<createRepositoryOutput>> {
    return this.request<createRepositoryOutput>("/api/v1/repositories", "POST", input, "application/json");
  }

  async getRepository(input: getRepositoryInput): Promise<ApiResponse<getRepositoryOutput>> {
    return this.request<getRepositoryOutput>("/api/v1/repositories/{owner}/{repo}", "GET", input);
  }

  async updateRepository(input: updateRepositoryInput): Promise<ApiResponse<updateRepositoryOutput>> {
    return this.request<updateRepositoryOutput>("/api/v1/repositories/{owner}/{repo}", "PATCH", input, "application/merge-patch+json");
  }

  async deleteRepository(input: deleteRepositoryInput): Promise<ApiResponse<deleteRepositoryOutput>> {
    return this.request<deleteRepositoryOutput>("/api/v1/repositories/{owner}/{repo}", "DELETE", input);
  }

  async listRefs(input: listRefsInput): Promise<ApiResponse<listRefsOutput>> {
    return this.request<listRefsOutput>("/api/v1/repositories/{owner}/{repo}/refs", "GET", input);
  }

  async getTree(input: getTreeInput): Promise<ApiResponse<getTreeOutput>> {
    return this.request<getTreeOutput>("/api/v1/repositories/{owner}/{repo}/tree/{ref}", "GET", input);
  }

  async getBlob(input: getBlobInput): Promise<ApiResponse<getBlobOutput>> {
    return this.request<getBlobOutput>("/api/v1/repositories/{owner}/{repo}/blob/{ref}", "GET", input);
  }

  async getRawContent(input: getRawContentInput): Promise<ApiResponse<getRawContentOutput>> {
    return this.request<getRawContentOutput>("/api/v1/repositories/{owner}/{repo}/raw/{ref}", "GET", input);
  }

  async listCommits(input: listCommitsInput): Promise<ApiResponse<listCommitsOutput>> {
    return this.request<listCommitsOutput>("/api/v1/repositories/{owner}/{repo}/commits", "GET", input);
  }

  async getCommit(input: getCommitInput): Promise<ApiResponse<getCommitOutput>> {
    return this.request<getCommitOutput>("/api/v1/repositories/{owner}/{repo}/commits/{sha}", "GET", input);
  }

  async compareRefs(input: compareRefsInput): Promise<ApiResponse<compareRefsOutput>> {
    return this.request<compareRefsOutput>("/api/v1/repositories/{owner}/{repo}/compare/{base}...{head}", "GET", input);
  }

  async getBlame(input: getBlameInput): Promise<ApiResponse<getBlameOutput>> {
    return this.request<getBlameOutput>("/api/v1/repositories/{owner}/{repo}/blame/{ref}", "GET", input);
  }

  async downloadArchive(input: downloadArchiveInput): Promise<ApiResponse<downloadArchiveOutput>> {
    return this.request<downloadArchiveOutput>("/api/v1/repositories/{owner}/{repo}/archive/{ref}", "GET", input);
  }

  async listIssues(input: listIssuesInput): Promise<ApiResponse<listIssuesOutput>> {
    return this.request<listIssuesOutput>("/api/v1/repositories/{owner}/{repo}/issues", "GET", input);
  }

  async createIssue(input: createIssueInput): Promise<ApiResponse<createIssueOutput>> {
    return this.request<createIssueOutput>("/api/v1/repositories/{owner}/{repo}/issues", "POST", input, "application/json");
  }

  async getIssue(input: getIssueInput): Promise<ApiResponse<getIssueOutput>> {
    return this.request<getIssueOutput>("/api/v1/repositories/{owner}/{repo}/issues/{number}", "GET", input);
  }

  async updateIssue(input: updateIssueInput): Promise<ApiResponse<updateIssueOutput>> {
    return this.request<updateIssueOutput>("/api/v1/repositories/{owner}/{repo}/issues/{number}", "PATCH", input, "application/json");
  }

  async listIssueComments(input: listIssueCommentsInput): Promise<ApiResponse<listIssueCommentsOutput>> {
    return this.request<listIssueCommentsOutput>("/api/v1/repositories/{owner}/{repo}/issues/{number}/comments", "GET", input);
  }

  async createIssueComment(input: createIssueCommentInput): Promise<ApiResponse<createIssueCommentOutput>> {
    return this.request<createIssueCommentOutput>("/api/v1/repositories/{owner}/{repo}/issues/{number}/comments", "POST", input, "application/json");
  }

  async listLabels(input: listLabelsInput): Promise<ApiResponse<listLabelsOutput>> {
    return this.request<listLabelsOutput>("/api/v1/repositories/{owner}/{repo}/labels", "GET", input);
  }

  async createLabel(input: createLabelInput): Promise<ApiResponse<createLabelOutput>> {
    return this.request<createLabelOutput>("/api/v1/repositories/{owner}/{repo}/labels", "POST", input, "application/json");
  }

  async listMilestones(input: listMilestonesInput): Promise<ApiResponse<listMilestonesOutput>> {
    return this.request<listMilestonesOutput>("/api/v1/repositories/{owner}/{repo}/milestones", "GET", input);
  }

  async listPullRequests(input: listPullRequestsInput): Promise<ApiResponse<listPullRequestsOutput>> {
    return this.request<listPullRequestsOutput>("/api/v1/repositories/{owner}/{repo}/pulls", "GET", input);
  }

  async createPullRequest(input: createPullRequestInput): Promise<ApiResponse<createPullRequestOutput>> {
    return this.request<createPullRequestOutput>("/api/v1/repositories/{owner}/{repo}/pulls", "POST", input, "application/json");
  }

  async getPullRequest(input: getPullRequestInput): Promise<ApiResponse<getPullRequestOutput>> {
    return this.request<getPullRequestOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}", "GET", input);
  }

  async updatePullRequest(input: updatePullRequestInput): Promise<ApiResponse<updatePullRequestOutput>> {
    return this.request<updatePullRequestOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}", "PATCH", input, "application/json");
  }

  async listPullRequestFiles(input: listPullRequestFilesInput): Promise<ApiResponse<listPullRequestFilesOutput>> {
    return this.request<listPullRequestFilesOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/files", "GET", input);
  }

  async listPullRequestReviews(input: listPullRequestReviewsInput): Promise<ApiResponse<listPullRequestReviewsOutput>> {
    return this.request<listPullRequestReviewsOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/reviews", "GET", input);
  }

  async submitPullRequestReview(input: submitPullRequestReviewInput): Promise<ApiResponse<submitPullRequestReviewOutput>> {
    return this.request<submitPullRequestReviewOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/reviews", "POST", input, "application/json");
  }

  async getPullRequestChecks(input: getPullRequestChecksInput): Promise<ApiResponse<getPullRequestChecksOutput>> {
    return this.request<getPullRequestChecksOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/checks", "GET", input);
  }

  async mergePullRequest(input: mergePullRequestInput): Promise<ApiResponse<mergePullRequestOutput>> {
    return this.request<mergePullRequestOutput>("/api/v1/repositories/{owner}/{repo}/pulls/{number}/merge", "POST", input, "application/json");
  }

  async listReleases(input: listReleasesInput): Promise<ApiResponse<listReleasesOutput>> {
    return this.request<listReleasesOutput>("/api/v1/repositories/{owner}/{repo}/releases", "GET", input);
  }

  async createRelease(input: createReleaseInput): Promise<ApiResponse<createReleaseOutput>> {
    return this.request<createReleaseOutput>("/api/v1/repositories/{owner}/{repo}/releases", "POST", input, "application/json");
  }

  async listDiscussions(input: listDiscussionsInput): Promise<ApiResponse<listDiscussionsOutput>> {
    return this.request<listDiscussionsOutput>("/api/v1/repositories/{owner}/{repo}/discussions", "GET", input);
  }

  async createDiscussion(input: createDiscussionInput): Promise<ApiResponse<createDiscussionOutput>> {
    return this.request<createDiscussionOutput>("/api/v1/repositories/{owner}/{repo}/discussions", "POST", input, "application/json");
  }

  async listWikiPages(input: listWikiPagesInput): Promise<ApiResponse<listWikiPagesOutput>> {
    return this.request<listWikiPagesOutput>("/api/v1/repositories/{owner}/{repo}/wiki/pages", "GET", input);
  }

  async createWikiPage(input: createWikiPageInput): Promise<ApiResponse<createWikiPageOutput>> {
    return this.request<createWikiPageOutput>("/api/v1/repositories/{owner}/{repo}/wiki/pages", "POST", input, "application/json");
  }

  async listProjects(input: listProjectsInput): Promise<ApiResponse<listProjectsOutput>> {
    return this.request<listProjectsOutput>("/api/v1/repositories/{owner}/{repo}/projects", "GET", input);
  }

  async createProject(input: createProjectInput): Promise<ApiResponse<createProjectOutput>> {
    return this.request<createProjectOutput>("/api/v1/repositories/{owner}/{repo}/projects", "POST", input, "application/json");
  }

  async listWorkflows(input: listWorkflowsInput): Promise<ApiResponse<listWorkflowsOutput>> {
    return this.request<listWorkflowsOutput>("/api/v1/repositories/{owner}/{repo}/workflows", "GET", input);
  }

  async dispatchWorkflow(input: dispatchWorkflowInput): Promise<ApiResponse<dispatchWorkflowOutput>> {
    return this.request<dispatchWorkflowOutput>("/api/v1/repositories/{owner}/{repo}/workflows/{workflowId}/dispatch", "POST", input, "application/json");
  }

  async listWorkflowRuns(input: listWorkflowRunsInput): Promise<ApiResponse<listWorkflowRunsOutput>> {
    return this.request<listWorkflowRunsOutput>("/api/v1/repositories/{owner}/{repo}/runs", "GET", input);
  }

  async getWorkflowRun(input: getWorkflowRunInput): Promise<ApiResponse<getWorkflowRunOutput>> {
    return this.request<getWorkflowRunOutput>("/api/v1/repositories/{owner}/{repo}/runs/{runId}", "GET", input);
  }

  async cancelWorkflowRun(input: cancelWorkflowRunInput): Promise<ApiResponse<cancelWorkflowRunOutput>> {
    return this.request<cancelWorkflowRunOutput>("/api/v1/repositories/{owner}/{repo}/runs/{runId}", "DELETE", input);
  }

  async getSecurityOverview(input: getSecurityOverviewInput): Promise<ApiResponse<getSecurityOverviewOutput>> {
    return this.request<getSecurityOverviewOutput>("/api/v1/repositories/{owner}/{repo}/security", "GET", input);
  }

  async getRepositoryInsights(input: getRepositoryInsightsInput): Promise<ApiResponse<getRepositoryInsightsOutput>> {
    return this.request<getRepositoryInsightsOutput>("/api/v1/repositories/{owner}/{repo}/insights", "GET", input);
  }

  async getRepositoryAccess(input: getRepositoryAccessInput): Promise<ApiResponse<getRepositoryAccessOutput>> {
    return this.request<getRepositoryAccessOutput>("/api/v1/repositories/{owner}/{repo}/settings/access", "GET", input);
  }

  async replaceRepositoryAccess(input: replaceRepositoryAccessInput): Promise<ApiResponse<replaceRepositoryAccessOutput>> {
    return this.request<replaceRepositoryAccessOutput>("/api/v1/repositories/{owner}/{repo}/settings/access", "PUT", input, "application/json");
  }

  async getRepositoryCache(input: getRepositoryCacheInput): Promise<ApiResponse<getRepositoryCacheOutput>> {
    return this.request<getRepositoryCacheOutput>("/api/v1/repositories/{owner}/{repo}/settings/cache", "GET", input);
  }

  async updateRepositoryCachePolicy(input: updateRepositoryCachePolicyInput): Promise<ApiResponse<updateRepositoryCachePolicyOutput>> {
    return this.request<updateRepositoryCachePolicyOutput>("/api/v1/repositories/{owner}/{repo}/settings/cache", "PUT", input, "application/json");
  }

  async invalidateRepositoryCache(input: invalidateRepositoryCacheInput): Promise<ApiResponse<invalidateRepositoryCacheOutput>> {
    return this.request<invalidateRepositoryCacheOutput>("/api/v1/repositories/{owner}/{repo}/settings/cache/invalidate", "POST", input);
  }

  async listRepositoryRules(input: listRepositoryRulesInput): Promise<ApiResponse<listRepositoryRulesOutput>> {
    return this.request<listRepositoryRulesOutput>("/api/v1/repositories/{owner}/{repo}/settings/rules", "GET", input);
  }

  async listWebhooks(input: listWebhooksInput): Promise<ApiResponse<listWebhooksOutput>> {
    return this.request<listWebhooksOutput>("/api/v1/repositories/{owner}/{repo}/settings/hooks", "GET", input);
  }

  async createWebhook(input: createWebhookInput): Promise<ApiResponse<createWebhookOutput>> {
    return this.request<createWebhookOutput>("/api/v1/repositories/{owner}/{repo}/settings/hooks", "POST", input, "application/json");
  }

  async listNotifications(input: listNotificationsInput): Promise<ApiResponse<listNotificationsOutput>> {
    return this.request<listNotificationsOutput>("/api/v1/notifications", "GET", input);
  }

  async markNotificationsRead(input: markNotificationsReadInput): Promise<ApiResponse<markNotificationsReadOutput>> {
    return this.request<markNotificationsReadOutput>("/api/v1/notifications", "PATCH", input, "application/json");
  }

  async search(input: searchInput): Promise<ApiResponse<searchOutput>> {
    return this.request<searchOutput>("/api/v1/search", "GET", input);
  }

  async streamEvents(input: streamEventsInput): Promise<ApiResponse<streamEventsOutput>> {
    return this.request<streamEventsOutput>("/api/v1/events/stream", "GET", input);
  }
}
